### ISSUE TITLE
labeled loops: newlines between label and loop

### ISSUE THREAD

**Issue by Famlam** [tntim96/JSCover#173] opened 2015-01-04 13:26 UTC
Hi,

Using the following code:
```html
<html><head></head><body><script src="test.js"></script>Check console</html>
```
with test.js:
```js
top:
  for (i=0; i<10; i++) {
    for (j=0; j<10; j++) {
      console.log(i,j);
      continue top;
    }
  }
  console.log("done!")
```

and calling JSCover 1.0.15 using: (Win 8)
```
"C:\Program Files (x86)\Java\jre7\bin\java.exe" -jar "JSCover\target\dist\JSCover-all.jar" -ws --report-dir="JSCover\output"
```

you get the following error in the console for the 4th line: 
```Uncaught SyntaxError: Undefined label 'top'```

This is because JSCover inserts a block `{` after the top, meaning that the `top` label is no longer connected to the for loop, and therefore the `top` in the `continue` statement does no longer reference to anything that can be continued. Using JSCover, the code looks like:
```js
top:
  {
    _$jscoverage['/test.js'].lineData[2]++;
    for (i = 0; visit1_2_1(i < 10); i++) {
      _$jscoverage['/test.js'].lineData[3]++;
      for (j = 0; visit2_3_1(j < 10); j++) {
        _$jscoverage['/test.js'].lineData[4]++;
        console.log(i, j);
        _$jscoverage['/test.js'].lineData[5]++;
        continue top;
      }
    }
  }
_$jscoverage['/test.js'].lineData[8]++;
console.log("done!");
```

This is a regression as it worked fine in 1.0.12. (Didn't check 1.0.13 or 1.0.14).

Thanks!

**Comment by tntim96** [comment] 2015-01-05 08:27
Thanks for the report. I think this was caused by the fix for https://github.com/tntim96/JSCover/issues/165 - I'll try to solve both and put in a better test to prevent the regression.

**Comment by tntim96** [comment] 2015-01-06 07:05
This should be fixed. Can you re-test from source, or using the latest artifacts at https://drone.io/github.com/tntim96/JSCover/files?

**Closed** 2015-01-06 08:18 UTC
Labels: bug, Fix applied - please re-test

**Comment by Famlam** [comment] 2015-01-06 09:18
Confirmed fixed. Thanks!
