### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by yanghaitaorj** [tntim96/JSCover#261] opened 2017-08-04 03:28 UTC
instrument web application in --local-storage file mode,throw "Exception in thread" when i execute jscover-filesystem.sh. Below is the response stacktrace
<pre><code>
Exception in thread "pool-2-thread-220" java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:583)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:106)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:992)
	at com.google.javascript.jscomp.CodeGenerator.addExpr(CodeGenerator.java:1561)
	at com.google.javascript.jscomp.CodeGenerator.addStringKey(CodeGenerator.java:1636)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:960)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:106)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:992)
	at com.google.javascript.jscomp.CodeGenerator.addExpr(CodeGenerator.java:1561)
	at com.google.javascript.jscomp.CodeGenerator.addList(CodeGenerator.java:1605)
	at com.google.javascript.jscomp.CodeGenerator.addList(CodeGenerator.java:1593)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:821)
	at com.google.javascript.jscomp.CodeGenerator.addExpr(CodeGenerator.java:1561)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:149)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:934)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:638)
	at com.google.javascript.jscomp.CodeGenerator.add(CodeGenerator.java:106)
	at com.google.javascript.jscomp.CodePrinter.toSource(CodePrinter.java:875)
	at com.google.javascript.jscomp.CodePrinter.access$300(CodePrinter.java:42)
	at com.google.javascript.jscomp.CodePrinter$Builder.build(CodePrinter.java:821)
	at jscover.instrument.SourceProcessor.instrumentSource(SourceProcessor.java:475)
	at jscover.instrument.SourceProcessor.processSourceWithoutHeader(SourceProcessor.java:435)
	at jscover.instrument.SourceProcessor.processSource(SourceProcessor.java:423)
	at jscover.instrument.SourceProcessor.processSourceForFileSystem(SourceProcessor.java:415)
	at jscover.instrument.InstrumenterService.instrumentJSForFileSystem(InstrumenterService.java:381)
	at jscover.filesystem.FileSystemInstrumenter$3.run(FileSystemInstrumenter.java:425)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</code></pre>
I look forward to your early reply

**Comment by tntim96** [comment] 2017-08-04 03:53
Can you provide the JavaScript snippet that causes this?

**Comment by yanghaitaorj** [comment] 2017-08-04 07:22
just one js file,throw exception,and create fail in taget file
[test.zip](https://github.com/tntim96/JSCover/files/1199520/test.zip)

**Comment by tntim96** [comment] 2017-08-04 07:57
This looks like a duplicate of https://github.com/tntim96/JSCover/issues/260. Can you build from the latest source to test or use the latest 2.0.2-SNAPSHOT?

If all OK, I'll release the fix soon.

**Comment by tntim96** [comment] 2017-08-04 08:22
Thanks for the report - looking into it now.

**Comment by tntim96** [comment] 2017-08-04 09:43
This doesn't look like valid JavaScript:

```JavaScript
    mounted () {
        this.onReady();
    },
```

**Comment by yanghaitaorj** [comment] 2017-08-04 09:51
this is vue.js component, writen with JavaScript es6 ,

**Comment by tntim96** [comment] 2017-08-04 11:51
Yep. Think that's fixed now. Can you build from source to test or use the latest 2.0.2-SNAPSHOT?

**Comment by yanghaitaorj** [comment] 2017-08-04 12:53
Thanks a lot,but sorry for that i do not konw how to build from source to test =. =

**Comment by tntim96** [comment] 2017-08-04 13:00
I've uploaded to http://jscover.sourceforge.net/latest/JSCover-all.jar. Let me know how that goes.

**Comment by tntim96** [comment] 2017-08-05 04:41
I've released a fix. Let me know if there are any problems.

**Closed by tntim96** 2017-08-05 04:41 UTC
Labels: bug, Fix applied - please re-test

**Comment by yanghaitaorj** [comment] 2017-08-05 05:55
Next monday i'll test it,thanks,have a good weekend

**Comment by yanghaitaorj** [comment] 2017-08-07 02:22
Test OK ,Thanks
